CREATE SCHEMA IF NOT EXISTS hrm_qiyerenyuan;

CREATE TABLE IF NOT EXISTS hrm_qiyerenyuan.accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT,
  password_hash TEXT,
  password_salt TEXT,
  display_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (role, username)
);

ALTER TABLE hrm_qiyerenyuan.accounts ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE hrm_qiyerenyuan.accounts ADD COLUMN IF NOT EXISTS password_salt TEXT;
ALTER TABLE hrm_qiyerenyuan.accounts ALTER COLUMN password DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS accounts_username_unique ON hrm_qiyerenyuan.accounts (username);

CREATE TABLE IF NOT EXISTS hrm_qiyerenyuan.staff_roles (
  staff_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (staff_id, role_id)
);

CREATE TABLE IF NOT EXISTS hrm_qiyerenyuan.role_menus (
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE IF NOT EXISTS hrm_qiyerenyuan.files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  original_name TEXT NOT NULL,
  content_type TEXT NOT NULL,
  size BIGINT NOT NULL,
  content_base64 TEXT NOT NULL,
  uploader TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS hrm_qiyerenyuan.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key TEXT NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  status TEXT,
  owner TEXT,
  amount NUMERIC DEFAULT 0,
  description TEXT,
  extra JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO hrm_qiyerenyuan.accounts (id, role, username, password, password_hash, password_salt, display_name) VALUES
  (1, 'admin', 'admin', NULL, 'sHWpNJ35GvCHdvsfYs-uhNr-otpvMWW9RpDh-JV4Sl4', 'admin-demo-salt', '系统管理员'),
  (2, 'user', 'employee01', NULL, 'aIBU1KA_KyZXYefYlMxMZlRsT46xHxnhFTYOjOoFCRw', 'employee-demo-salt', '普通员工'),
  (3, 'staff', 'hr01', NULL, '8YSyjd5msUmPIVvLQ5NcEsa1_WfoBEsmhIDFSdJ2Wt0', 'staff-demo-salt', '人事专员')
ON CONFLICT (role, username) DO UPDATE SET
  password = NULL,
  password_hash = COALESCE(hrm_qiyerenyuan.accounts.password_hash, EXCLUDED.password_hash),
  password_salt = COALESCE(hrm_qiyerenyuan.accounts.password_salt, EXCLUDED.password_salt),
  display_name = EXCLUDED.display_name;

INSERT INTO hrm_qiyerenyuan.staff_roles (staff_id, role_id) VALUES (1, 1), (2, 3), (3, 2)
ON CONFLICT DO NOTHING;

INSERT INTO hrm_qiyerenyuan.role_menus (role_id, menu_id) VALUES
  (1,1),(1,11),(1,12),(1,13),(1,2),(1,21),(1,22),(1,3),(1,31),(1,32),(1,33),(1,4),(1,41),(1,42),
  (2,1),(2,11),(2,12),(2,13),(2,2),(2,21),(2,22),(2,3),(2,31),(2,32),(2,33),
  (3,1),(3,11),(3,13),(3,2),(3,21),(3,22),(3,3),(3,32),(3,33)
ON CONFLICT DO NOTHING;

INSERT INTO hrm_qiyerenyuan.items (id, module_key, title, subtitle, status, owner, amount, description, extra) VALUES
  (1, 'employee', '员工管理演示记录1', '员工档案、岗位、入职和在职状态', '进行中', '系统管理员', 10, '企业人员与人力资源管理系统的员工管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (2, 'employee', '员工管理演示记录2', '员工档案、岗位、入职和在职状态', '待处理', '普通员工', 20, '企业人员与人力资源管理系统的员工管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (3, 'employee', '员工管理演示记录3', '员工档案、岗位、入职和在职状态', '已完成', '人事专员', 30, '企业人员与人力资源管理系统的员工管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (4, 'department', '部门管理演示记录1', '组织部门、负责人和人员编制', '进行中', '系统管理员', 10, '企业人员与人力资源管理系统的部门管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (5, 'department', '部门管理演示记录2', '组织部门、负责人和人员编制', '待处理', '普通员工', 20, '企业人员与人力资源管理系统的部门管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (6, 'department', '部门管理演示记录3', '组织部门、负责人和人员编制', '已完成', '人事专员', 30, '企业人员与人力资源管理系统的部门管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (7, 'attendance', '考勤管理演示记录1', '打卡、迟到、缺勤和考勤统计', '进行中', '系统管理员', 10, '企业人员与人力资源管理系统的考勤管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (8, 'attendance', '考勤管理演示记录2', '打卡、迟到、缺勤和考勤统计', '待处理', '普通员工', 20, '企业人员与人力资源管理系统的考勤管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (9, 'attendance', '考勤管理演示记录3', '打卡、迟到、缺勤和考勤统计', '已完成', '人事专员', 30, '企业人员与人力资源管理系统的考勤管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (10, 'leave', '请假审批演示记录1', '请假申请、审批流程和状态跟踪', '进行中', '系统管理员', 10, '企业人员与人力资源管理系统的请假审批模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (11, 'leave', '请假审批演示记录2', '请假申请、审批流程和状态跟踪', '待处理', '普通员工', 20, '企业人员与人力资源管理系统的请假审批模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (12, 'leave', '请假审批演示记录3', '请假申请、审批流程和状态跟踪', '已完成', '人事专员', 30, '企业人员与人力资源管理系统的请假审批模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (13, 'salary', '薪资管理演示记录1', '工资、社保、绩效和发放记录', '进行中', '系统管理员', 10, '企业人员与人力资源管理系统的薪资管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (14, 'salary', '薪资管理演示记录2', '工资、社保、绩效和发放记录', '待处理', '普通员工', 20, '企业人员与人力资源管理系统的薪资管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (15, 'salary', '薪资管理演示记录3', '工资、社保、绩效和发放记录', '已完成', '人事专员', 30, '企业人员与人力资源管理系统的薪资管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (16, 'permission', '权限管理演示记录1', '角色、菜单和系统访问权限', '进行中', '系统管理员', 10, '企业人员与人力资源管理系统的权限管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (17, 'permission', '权限管理演示记录2', '角色、菜单和系统访问权限', '待处理', '普通员工', 20, '企业人员与人力资源管理系统的权限管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (18, 'permission', '权限管理演示记录3', '角色、菜单和系统访问权限', '已完成', '人事专员', 30, '企业人员与人力资源管理系统的权限管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  module_key = EXCLUDED.module_key,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  status = EXCLUDED.status,
  owner = EXCLUDED.owner,
  amount = EXCLUDED.amount,
  description = EXCLUDED.description,
  extra = EXCLUDED.extra,
  updated_at = now();

SELECT setval(pg_get_serial_sequence('hrm_qiyerenyuan.accounts', 'id'), COALESCE((SELECT MAX(id) FROM hrm_qiyerenyuan.accounts), 1), true);
SELECT setval(pg_get_serial_sequence('hrm_qiyerenyuan.items', 'id'), COALESCE((SELECT MAX(id) FROM hrm_qiyerenyuan.items), 1), true);

DELETE FROM hrm_qiyerenyuan.items AS item
WHERE item.module_key = 'hrm_docs'
  AND NOT EXISTS (
    SELECT 1 FROM hrm_qiyerenyuan.files AS file
    WHERE file.name = item.extra ->> 'name'
  );

CREATE OR REPLACE FUNCTION public.hrm_qiyerenyuan_rest(
  p_table_name TEXT,
  p_method TEXT DEFAULT 'GET',
  p_query JSONB DEFAULT '{}'::jsonb,
  p_payload JSONB DEFAULT '{}'::jsonb
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_schema CONSTANT TEXT := 'hrm_qiyerenyuan';
  v_table TEXT;
  v_sql TEXT;
  v_rows JSONB := '[]'::jsonb;
  v_key TEXT;
  v_value TEXT;
  v_where TEXT := '';
  v_order TEXT := '';
  v_limit TEXT := '';
  v_set TEXT := '';
  v_columns TEXT := '';
  v_values TEXT := '';
BEGIN
  IF p_table_name NOT IN ('accounts', 'items', 'staff_roles', 'role_menus', 'files') THEN
    RAISE EXCEPTION 'table is not allowed: %', p_table_name;
  END IF;

  v_table := format('%I.%I', v_schema, p_table_name);

  FOR v_key, v_value IN SELECT key, value #>> '{}' FROM jsonb_each(p_query)
  LOOP
    IF v_key = 'select' THEN
      CONTINUE;
    ELSIF v_key = 'order' THEN
      v_order := ' ORDER BY ' || quote_ident(split_part(v_value, '.', 1)) ||
        CASE WHEN lower(split_part(v_value, '.', 2)) = 'desc' THEN ' DESC' ELSE ' ASC' END;
    ELSIF v_key = 'limit' THEN
      v_limit := ' LIMIT ' || LEAST(GREATEST(v_value::int, 1), 200);
    ELSIF v_value LIKE 'eq.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' = ' || quote_literal(substring(v_value FROM 4));
    ELSIF v_value LIKE 'ilike.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' ILIKE ' || quote_literal(substring(v_value FROM 7));
    END IF;
  END LOOP;

  IF upper(p_method) = 'GET' THEN
    v_sql := 'SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM (SELECT * FROM ' || v_table || v_where || v_order || v_limit || ') t';
    EXECUTE v_sql INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'POST' THEN
    SELECT string_agg(quote_ident(key), ', '), string_agg(quote_literal(value #>> '{}'), ', ')
      INTO v_columns, v_values
    FROM jsonb_each(p_payload)
    WHERE key <> 'id';
    IF v_columns IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'INSERT INTO ' || v_table || ' (' || v_columns || ') VALUES (' || v_values || ') RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'PATCH' THEN
    SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value #>> '{}'), ', ')
      INTO v_set
    FROM jsonb_each(p_payload)
    WHERE key <> 'id' AND key <> 'created_at';
    IF v_set IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'UPDATE ' || v_table || ' SET ' || v_set || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'DELETE' THEN
    v_sql := 'DELETE FROM ' || v_table || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  END IF;

  RAISE EXCEPTION 'method is not allowed: %', p_method;
END;
$$;

REVOKE ALL ON FUNCTION public.hrm_qiyerenyuan_rest(TEXT, TEXT, JSONB, JSONB) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.hrm_qiyerenyuan_rest(TEXT, TEXT, JSONB, JSONB) TO service_role;
DROP FUNCTION IF EXISTS public.hrm_qiyerenyuan_demo_rest(TEXT, TEXT, JSONB, JSONB);
